name: Cron

on:
  schedule:
    - cron:  '*/30 * * * *'  # execute at every 30th minute (e.g. 00:00 and 00:30)

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Execute
      run: ./execute.sh ${{secrets.API_KEY}} ${{secrets.API_SECRET_KEY}} ${{secrets.ACCESS_TOKEN}} ${{secrets.ACCESS_TOKEN_SECRET}}
